---
title: "Modification of the beed function"
output: word_document
date: "2023-08-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Modified functions: run the whole code block.
```{r}
# Modified "madogram" function
madogram.mod <- function (w, data, margin = c("emp", "est", "exp", "frechet", 
    "gumbel")) 
{
    lmadogram <- function(w, data, margin) {
        sumdata <- dim(data)
        d <- sumdata[2]
        if (!is.matrix(w)) 
            w <- matrix(w, ncol = d)
        sumw <- dim(w)
        if (sumw[2] != d) 
            stop("`x' must be a vector/matrix with `d' elements/columns")
        if (length(margin) > 1) 
            margin = "emp"
        ans <- numeric(sumw[1])
        if (margin == "emp") {
            data_emp <- apply(data, 2, rank, na.last = "keep")
            nasm <- apply(data_emp, 2, function(x) sum(!is.na(x)))
            data_emp <- data_emp/rep(nasm, each = nrow(data_emp))
            Fdata <- data_emp
        }
        if (margin == "est") {
            par <- NULL
            Fdata <- data
            for (i in 1:d) {
              ###################################################
              # modified part:
               param <- extRemes::fevd(data[,i], type = "GEV", 
                             method = "MLE")$results$par
                Fdata[, i] <- evd :: pgev(q = data[, i], loc = param[1], 
                  scale = param[2], shape = param[3])
                ####################################################
            }
        }
        if (margin == "exp") {
            Fdata <- apply(data, 2, pexp)
        }
        if (margin == "frechet") {
            Fdata <- apply(data, 2, pfrechet)
        }
        if (margin == "gumbel") {
            Fdata <- apply(data, 2, pgumbel)
        }
        powerw <- function(j, xx, w, d) sapply(c(1:d), function(i, 
            x, w) x[, i]^(1/w[, i]), xx, t(w[j, ]))
        u <- lapply(c(1:sumw[1]), powerw, Fdata, w, d)
        ma <- sapply(c(1:sumw[1]), function(i, u) apply(u[[i]], 
            1, max), u)
        me <- sapply(c(1:sumw[1]), function(i, u) rowMeans(u[[i]]), 
            u)
        mm <- ma - me
        ans <- colMeans(mm)
        return(ans)
    }
    ans <- lmadogram(w, data, margin)
    sumdata <- dim(data)
    d <- sumdata[2]
    if (!is.matrix(w)) 
        w <- matrix(w, ncol = d)
    W <- w/(1 + w)
    cst <- rowMeans(W)
    A <- ((cst + ans)/(1 - cst - ans))
    return(A)
}


# Modified "beed" function

beed.mod <- function (data, x, d = 3, est = c("ht", "cfg", "md", "pick"), 
    margin = c("emp", "est", "exp", "frechet", "gumbel"), k = 13, 
    y = NULL, beta = NULL, plot = FALSE, colour.choice = 1, lwd.choice = 1, lty.choice = 1) 
{
    datadim <- dim(data)
    xdim <- dim(x)
    if (d != datadim[2]) 
        stop("`data' must be a matrix with `d' columns")
    if (!is.matrix(x) || xdim[2] != d) 
        stop("`x' must be a matrix with `d' columns")
    if (any(x < 0, na.rm = TRUE)) 
        stop("`x' must be non-negative")
    rs <- rowSums(x)
    nx <- xdim[1]
    if (any(rs < 0, na.rm = TRUE)) 
        warning("row(s) of `x' which do not lay in the simplex are removed")
    index <- function(k, d) {
        beta.index <- expand.grid(rep(list(0:k), d))
        beta.index.sum <- rowSums(beta.index)
        restr <- which(beta.index.sum <= k)
        v <- as.matrix(beta.index[restr, ncol(beta.index):1])
        return(v)
    }
    if (d == 2) {
        xx <- as.matrix(x[, -d])
        vb <- index(k = k, d - 1)
        q <- nrow(vb)
        Z <- ExtremalDep:::bp(x = x, k = k, v = vb)
        if (is.null(y)) {
            if (length(est) > 1) {
                est = "md"
                warning("invalid argument for `est', madogram by default")
            }
            if (length(margin) > 1) {
                margin = "emp"
                warning("invalid argument for `margin', empirical transformation dy default")
            }
          # replaced `madogram` with `madogram.mod`
            if (margin == "emp") 
                y <- switch(est, ht = abvnonpar(x = xx, data = data, 
                  method = "pickands", d = d, madj = 2, epmar = TRUE), 
                  md = madogram.mod(w = x, data = data, margin = "emp"), 
                  pick = An.biv(x = data, w = xx, estimator = "Pickands"), 
                  cfg = An.biv(x = data, w = xx, estimator = "CFG"))
            if (margin == "est") 
                y <- switch(est, ht = abvnonpar(x = xx, data = data, 
                  method = "pickands", d = d, madj = 2, epmar = FALSE), 
                  md = madogram.mod(w = x, data = data, margin = "est"), 
                  pick = An.biv(x = data, w = xx, estimator = "Pickands"), 
                  cfg = An.biv(x = data, w = xx, estimator = "CFG"))
            if ((margin != "emp") & (margin != "est")) {
                y <- switch(est, ht = abvnonpar(x = xx, data = data, 
                  method = "pickands", d = d, madj = 2, epmar = FALSE), 
                  md = madogram.mod(w = x, data = data, margin = margin), 
                  pick = An.biv(x = data, w = xx, estimator = "Pickands"), 
                  cfg = An.biv(x = data, w = xx, estimator = "CFG"))
                if ((est == "ht") | (est == "pick") | (est == 
                  "cfg")) 
                  warning("Marginal distributions estimated")
            }
        }
        n <- length(y)
        if (is.null(beta)) {
            R1 <- matrix(0, k - 1, k + 1)
            for (i in 1:(k - 1)) R1[i, i:(i + 2)] <- c(1, -2, 
                1)
            r1 <- rep(0, nrow(R1))
            R2 <- matrix(0, 2 * d, q)
            vertix <- which(apply(vb, 1, function(x) any(x == 
                k)))
            R2[1, 1] <- 1
            R2[(d + 1), 1] <- -1
            for (i in 1:(d - 1)) {
                R2[i + 1, vertix[i]] <- 1
                R2[i + 1 + d, vertix[i]] <- -1
            }
            r2 <- c(rep(1, d), rep(-1, d))
            nr <- d * (d - 1)
            R3 <- matrix(0, nr, q)
            vertix_10 <- which(vb == 1)
            vertix_k_10 <- which(vb == k - 1)
            vertix <- c(vertix_10, vertix_k_10)
            for (i in 1:nr) R3[i, vertix[i]] <- 1
            r3 <- rep(1 - 1/k, nr)
            R = rbind(R1, R2, R3)
            r0 = c(r1, r2, r3)
            Dmat <- t(Z) %*% Z
            dvec <- t(y) %*% Z
            Rmat <- t(R)
            fit <- quadprog:::solve.QP(Dmat, dvec, Rmat, r0)
            beta.tilde <- as.matrix(fit$solution)
        }
        else beta.tilde <- beta
        y.tilde <- Z %*% beta.tilde
        yy <- y
        if (plot == TRUE) {
            plot(x[, 1], x[, 2], type = "n", xlab = "t", ylab = "A(t)", 
                ylim = c(0.5, 1))
            polygon(c(0, 0.5, 1), c(1, 0.5, 1), lty = 1, lwd = 1, 
                border = "grey")
            lines(x[, 1], y.tilde, lty = lty.choice, col = colour.choice, lwd = lwd.choice)
        }
    }
    else {
        zero1 <- which(rs > 1)
        zero0 <- which(rs == 0)
        zeroNa <- which(is.na(rs))
        if ((length(zero1) == 0) & (length(zeroNa) == 0) & (length(zero0) == 
            0)) 
            X <- x
        else {
            X <- x[-c(zero1, zeroNa, zero0), ]
        }
        xx <- as.matrix(X[, -d])
        vb <- index(k, d - 1)
        q <- nrow(vb)
        Z <- ExtremalDep:::bp(x = X, k = k, v = vb)
        if (is.null(y)) {
            if (length(est) > 1) {
                est = "md"
                warning("invalid argument for `est', madogram by default")
            }
            if (length(margin) > 1) {
                margin = "emp"
                warning("invalid argument for `margin', empirical transformation dy default")
            }
          # replaced `madogram` with `madogram.mod`
            if (margin == "emp") 
                y <- switch(est, ht = amvnonpar(x = X, data = data, 
                  d = d, madj = 2, epmar = TRUE), md = madogram.mod(w = X, 
                  data = data, margin = "emp"), cfg = An(x = data, 
                  w = X)$CFG, pick = An(x = data, w = X)$P)
            if (margin == "est") 
                y <- switch(est, ht = amvnonpar(x = X, data = data, 
                  d = d, madj = 2, epmar = FALSE), md = madogram.mod(w = X, 
                  data = data, margin = "est"), cfg = An(x = data, 
                  w = X)$CFG, pick = An(x = data, w = X)$P)
            if ((margin != "emp") & (margin != "est")) {
                y <- switch(est, ht = amvnonpar(x = X, data = data, 
                  d = d, madj = 2, epmar = FALSE), md = madogram.mod(w = X, 
                  data = data, margin = margin), cfg = An(x = data, 
                  w = X)$CFG, pick = An(x = data, w = X)$P)
                if ((est == "ht") | (est == "pick") | (est == 
                  "cfg")) 
                  warning("Marginal distributions estimated")
            }
        }
        n <- length(y)
        yy <- rep(NA, nx)
        if ((length(zero1) == 0) & (length(zeroNa) == 0) & (length(zero0) == 
            0)) 
            yy <- y
        else yy[-c(zero1, zeroNa, zero0)] <- y
        if (is.null(beta)) {
            R1 <- convexity_old(v = vb, d = d)
            r1 <- rep(0, nrow(R1))
            R2 <- matrix(0, 2 * d, q)
            vertix <- which(apply(vb, 1, function(x) any(x == 
                k)))
            R2[1, 1] <- 1
            R2[(d + 1), 1] <- -1
            for (i in 1:(d - 1)) {
                R2[i + 1, vertix[i]] <- 1
                R2[i + 1 + d, vertix[i]] <- -1
            }
            r2 <- c(rep(1, d), rep(-1, d))
            if (d == 3) {
                nr <- d * (d - 1)
                R3 <- matrix(0, nr, q)
                v_10 <- which(apply(vb, 1, function(x) any(x == 
                  1) & any(x == 0) & sum(x) == 1))
                v_k_10 <- which(apply(vb, 1, function(x) any(x == 
                  k - 1) & any(x == 0) & sum(x) == k - 1))
                v_k_11 <- which(apply(vb, 1, function(x) any(x == 
                  k - 1) & any(x == 1) & sum(x) == k))
                vertix <- c(v_10, v_k_10, v_k_11)
                for (i in 1:nr) R3[i, vertix[i]] <- 1
                r3 <- rep(1 - 1/k, nr)
            }
            if (d > 3) {
                R3 <- Z
                r3 <- apply(X, 1, max)
            }
            R = rbind(R1, R2, R3)
            r0 = c(r1, r2, r3)
            Dmat <- t(Z) %*% Z
            dvec <- t(y) %*% Z
            Rmat <- t(R)
            fit <- quadprog:::solve.QP(Dmat, dvec, Rmat, r0)
            beta.tilde <- as.matrix(fit$solution)
        }
        else beta.tilde <- beta
        y.tilde <- rep(NA, nx)
        if ((length(zero1) == 0) & (length(zeroNa) == 0) & (length(zero0) == 
            0)) 
            y.tilde <- Z %*% beta.tilde
        else y.tilde[-c(zero1, zeroNa, zero0)] <- Z %*% beta.tilde
        if (plot == TRUE) {
            if (d == 3) {
                if ((length(zero1) == 0) & (length(zeroNa) == 
                  0) & (length(zero0) == 0)) {
                  numg <- round((-1 + sqrt(1 + 8 * xdim[1]))/2)
                  mat <- matrix(NA, numg, numg)
                  mat[lower.tri(mat, diag = T)] <- y.tilde
                }
                else {
                  numg <- sqrt(nx)
                  mat <- matrix(y.tilde, numg, numg)
                }
                xy <- seq(0, 1, length = numg)
                plot(xy, xy, type = "n", xlab = expression(t[1]), 
                  ylab = expression(t[2]))
                image(x = xy, y = xy, z = mat, col = heat.colors(numg), 
                  add = TRUE)
                contour(x = xy, y = xy, z = mat, add = T, col = "black", 
                  labcex = 0.6, lty = 1, cex = 2)
            }
            if (d >= 4) 
                warning("can not plot in high dimensions")
        }
    }
    med <- matrix(rep(1/d, d), ncol = d)
    Zmed <- ExtremalDep:::bp(med, v = vb, k = k)
    extind <- as.numeric(d * (Zmed %*% beta.tilde))
    out <- list(beta = beta.tilde, A = y.tilde, Anonconvex = yy, 
        extind = extind)
    return(out)
}


# tcplot() modification

tcplot.mod <- function (data, tlim, model = c("gpd", "pp"), pscale = FALSE, 
    cmax = FALSE, r = 1, ulow = -Inf, rlow = 1, nt = 25, which = 1:npar, 
    conf = 0.95, lty = 1, lwd = 1, type = "b", col.choice = "black", cilty = 1, cicol = "chocolate2", cilwd = 1, vci = TRUE, 
    xlab, xlim, ylabs, ylims, ask = nb.fig < length(which) && 
        dev.interactive(), ...) 
{
    model <- match.arg(model)
    u <- seq(tlim[1], tlim[2], length = nt)
    if (pscale) {
        tlim[1] <- mean(data <= tlim[1], na.rm = TRUE)
        tlim[2] <- mean(data <= tlim[2], na.rm = TRUE)
        pvec <- seq(tlim[1], tlim[2], length = nt)
        u <- my_percentile_func(data, prob = pvec)
    }
    locs <- scls <- shps <- matrix(NA, nrow = nt, ncol = 3)
    dimnames(locs) <- list(round(u, 2), c("lower", "loc", "upper"))
    dimnames(shps) <- list(round(u, 2), c("lower", "shape", "upper"))
    if (model == "gpd") {
        pname <- "mscale"
        npar <- 2
    }
    if (model == "pp") {
        pname <- "scale"
        npar <- 3
    }
    dimnames(scls) <- list(round(u, 2), c("lower", pname, "upper"))
    z <- fpot(data, u[1], model = model, cmax = cmax, r = r, 
        ulow = ulow, rlow = rlow, corr = TRUE, ...)
    stvals <- as.list(round(fitted(z), 3))
    for (i in 1:nt) {
        z <- fpot(data, u[i], model = model, start = stvals, 
            cmax = cmax, r = r, ulow = ulow, rlow = rlow, corr = TRUE, 
            ...)
        stvals <- as.list(fitted(z))
        mles <- fitted(z)
        stderrs <- std.errors(z)
        cnst <- qnorm((1 + conf)/2)
        shp <- mles["shape"]
        scl <- mles["scale"]
        shpse <- stderrs["shape"]
        sclse <- stderrs["scale"]
        if (model == "pp") {
            loc <- mles["loc"]
            locse <- stderrs["loc"]
            locs[i, ] <- c(loc - cnst * locse, loc, loc + cnst * 
                locse)
        }
        if (model == "gpd") {
            scl <- scl - shp * u[i]
            covar <- z$corr[1, 2] * prod(stderrs)
            sclse <- sqrt(sclse^2 - 2 * u[i] * covar + (u[i] * 
                shpse)^2)
        }
        scls[i, ] <- c(scl - cnst * sclse, scl, scl + cnst * 
            sclse)
        shps[i, ] <- c(shp - cnst * shpse, shp, shp + cnst * 
            shpse)
    }
    show <- rep(FALSE, npar)
    show[which] <- TRUE
    nb.fig <- prod(par("mfcol"))
    if (ask) {
        op <- par(ask = TRUE)
        on.exit(par(op))
    }
    if (pscale) 
        u <- pvec
    if (missing(xlim)) 
        xlim <- tlim
    if (missing(xlab)) {
        xlab <- "Threshold"
        if (pscale) 
            xlab <- "Threshold probability"
    }
    if (model == "pp") {
        ylab <- c("Location", "Scale", "Shape")
        if (!missing(ylabs)) 
            ylab[show] <- ylabs
        ylim <- rbind(range(locs), range(scls), range(shps))
        if (!missing(ylims)) 
            ylim[show, ] <- ylims
        if (show[1]) {
            matplot(u, locs, type = "n", xlab = xlab, ylab = ylab[1], 
                xlim = xlim, ylim = ylim[1, ])
            lines(u, locs[, 2], lty = lty, lwd = lwd, type = type)
            if (vci) 
                segments(u, locs[, 1], u, locs[, 3], lty = cilty)
            else {
                lines(u, locs[, 1], lty = cilty, col = cicol, lwd = cilwd)
                lines(u, locs[, 3], lty = cilty, col = cicol, lwd = cilwd)
            }
        }
        if (show[2]) {
            matplot(u, scls, type = "n", xlab = xlab, ylab = ylab[2], 
                xlim = xlim, ylim = ylim[2, ])
            lines(u, scls[, 2], lty = lty, lwd = lwd, type = type)
            if (vci) 
                segments(u, scls[, 1], u, scls[, 3], lty = cilty)
            else {
                lines(u, scls[, 1], lty = cilty, col = cicol, lwd = cilwd)
                lines(u, scls[, 3], lty = cilty, col = cicol, lwd = cilwd)
            }
        }
        if (show[3]) {
            matplot(u, shps, type = "n", xlab = xlab, ylab = ylab[3], 
                xlim = xlim, ylim = ylim[3, ])
            lines(u, shps[, 2], lty = lty, lwd = lwd, type = type)
            if (vci) 
                segments(u, shps[, 1], u, shps[, 3], lty = cilty)
            else {
                lines(u, shps[, 1], lty = cilty, col = cicol, lwd = cilwd)
                lines(u, shps[, 3], lty = cilty, col = cicol, lwd = cilwd)
            }
        }
        rtlist <- list(locs = locs, scales = scls, shapes = shps)
    }
    if (model == "gpd") {
        ylab <- c("Modified Scale", "Shape")
        if (!missing(ylabs)) 
            ylab[show] <- ylabs
        ylim <- rbind(range(scls), range(shps))
        if (!missing(ylims)) 
            ylim[show, ] <- ylims
        if (show[1]) {
            matplot(u, scls, type = "n", xlab = xlab, ylab = ylab[1], 
                xlim = xlim, ylim = ylim[1, ])
            lines(u, scls[, 2], lty = lty, lwd = lwd, type = type)
            if (vci) 
                segments(u, scls[, 1], u, scls[, 3], lty = cilty)
            else {
                lines(u, scls[, 1], lty = cilty, col = cicol, lwd = cilwd)
                lines(u, scls[, 3], lty = cilty, col = cicol, lwd = cilwd)
            }
        }
        if (show[2]) {
            matplot(u, shps, type = "n", xlab = xlab, ylab = ylab[2], 
                xlim = xlim, ylim = ylim[2, ])
            lines(u, shps[, 2], lty = lty, lwd = lwd, type = type, col = col.choice) # modified
            if (vci) 
                segments(u, shps[, 1], u, shps[, 3], lty = cilty)
            else {
                lines(u, shps[, 1], lty = cilty, col = cicol, lwd = cilwd)
                lines(u, shps[, 3], lty = cilty, col = cicol, lwd = cilwd)
            }
        }
        rtlist <- list(scales = scls, shapes = shps)
    }
    invisible(rtlist)
}


## Selection of threshold vector: bvtcplot modification

bvtcplot.mod <- function (x, spectral = FALSE, xlab, ylab, ...) 
{
    if (!is.matrix(x) && !is.data.frame(x)) 
        stop("`x' must be a matrix or data frame")
    if (ncol(x) != 2) 
        stop("`x' has incorrect number of columns")
    x <- x[complete.cases(x), ]
    nn <- nrow(x)
    ula <- apply(x, 2, rank)/(nn + 1)
    fla <- -1/log(ula)
    rr <- rowSums(fla)
    ww <- fla/rr
    rro <- sort(rr, decreasing = TRUE)[-1]
    k <- 1:(nn - 1)
    k0 <- max(which(rro * k/(2*nn) > 1))
    if (!spectral) {
        if (missing(xlab)) 
            xlab <- "k"
        if (missing(ylab)) 
            ylab <- "H([0,1])"
        plot(k, rro * k/(2*nn), xlab = xlab, ylab = ylab, ...)
        abline(h = 1)
        # abline(v = k0, lty = 2)
        return(invisible(list(x = k, y = rro * k/(2*nn), k0 = k0)))
    }
    xx <- yy <- seq(0, 1, len = 100)
    for (k in 1:100) yy[k] <- sum(rr > rro[k0] & ww[, 1] <= xx[k])
    if (missing(xlab)) 
        xlab <- "w"
    if (missing(ylab)) 
        ylab <- "H([0,w])"
    plot(xx, 2/k0 * yy, type = "l", xlab = xlab, ylab = ylab, 
        ...)
    abline(h = c(0, 1))
    return(invisible(list(x = xx, y = 1/k0 * yy, k0 = k0)))
}

# abvnonpar: pot method
abvnonpar.mod <- function (x = 0.5, data, epmar = FALSE, nsloc1 = NULL, nsloc2 = NULL, 
    method = c("cfg", "pickands", "tdo", "pot"), k = nrow(data)/4, 
    convex = FALSE, rev = FALSE, madj = 0, kmar = NULL, plot = FALSE, 
    add = FALSE, lty = 1, lwd = 1, col = 1, blty = 3, blwd = 1, 
    xlim = c(0, 1), ylim = c(0.5, 1), xlab = "t", ylab = "A(t)", 
    ...) 
{
    if (mode(x) != "numeric" || any(x < 0, na.rm = TRUE) || any(x > 
        1, na.rm = TRUE)) 
        stop("invalid argument for `x'")
    method <- match.arg(method)
    epdata <- apply(data, 2, rank, na.last = "keep")
    nasm <- apply(data, 2, function(x) sum(!is.na(x)))
    epdata <- epdata/rep(nasm + 1, each = nrow(data))
    epdata <- -log(epdata)
    if (epmar) 
        data <- epdata
    if (!epmar) {
        if (method == "pot") {
            if (any(k >= nasm)) 
                stop("k is too large")
            u1 <- sort(data[, 1], decreasing = TRUE)[(k/2) + 1]
            u2 <- sort(data[, 2], decreasing = TRUE)[(k/2) + 1]
            d1ab <- (data[, 1] > u1) & !is.na(data[, 1])
            d2ab <- (data[, 2] > u2) & !is.na(data[, 2])
            if (!is.null(kmar)) {
                data[d1ab, 1] <- mtransform(data[d1ab, 1], c(u1, 
                  kmar))
                data[d2ab, 2] <- mtransform(data[d2ab, 2], c(u2, 
                  kmar))
            }
            else {
                mle.m1 <- c(u1, fitted(fpot(data[d1ab, 1], threshold = u1)))
                mle.m2 <- c(u2, fitted(fpot(data[d2ab, 2], threshold = u2)))
                data[d1ab, 1] <- mtransform(data[d1ab, 1], mle.m1)
                data[d2ab, 2] <- mtransform(data[d2ab, 2], mle.m2)
            }
            data[d1ab, 1] <- -log(1 - (k/2) * data[d1ab, 1]/nasm[1])
            data[d2ab, 2] <- -log(1 - (k/2) * data[d2ab, 2]/nasm[2])
            data[!d1ab, 1] <- epdata[!d1ab, 1]
            data[!d2ab, 2] <- epdata[!d2ab, 2]
        }
        if (method != "pot") {
            if (!is.null(kmar)) {
                data <- mtransform(data, kmar)
            }
            else {
                if (!is.null(nsloc1)) {
                  if (is.vector(nsloc1)) 
                    nsloc1 <- data.frame(trend = nsloc1)
                  if (nrow(nsloc1) != nrow(data)) 
                    stop("`nsloc1' and data are not compatible")
                  nslocmat1 <- cbind(1, as.matrix(nsloc1))
                }
                if (!is.null(nsloc2)) {
                  if (is.vector(nsloc2)) 
                    nsloc2 <- data.frame(trend = nsloc2)
                  if (nrow(nsloc2) != nrow(data)) 
                    stop("`nsloc2' and data are not compatible")
                  nslocmat2 <- cbind(1, as.matrix(nsloc2))
                }
                mle.m1 <- fitted(fgev(data[, 1], nsloc = nsloc1, 
                  std.err = FALSE))
                loc.mle.m1 <- mle.m1[grep("^loc", names(mle.m1))]
                if (is.null(nsloc1)) 
                  loc.mle.m1 <- rep(loc.mle.m1, nrow(data))
                else loc.mle.m1 <- nslocmat1 %*% loc.mle.m1
                mle.m1 <- cbind(loc.mle.m1, mle.m1["scale"], 
                  mle.m1["shape"])
                mle.m2 <- fitted(fgev(data[, 2], nsloc = nsloc2, 
                  std.err = FALSE))
                loc.mle.m2 <- mle.m2[grep("^loc", names(mle.m2))]
                if (is.null(nsloc2)) 
                  loc.mle.m2 <- rep(loc.mle.m2, nrow(data))
                else loc.mle.m2 <- nslocmat2 %*% loc.mle.m2
                mle.m2 <- cbind(loc.mle.m2, mle.m2["scale"], 
                  mle.m2["shape"])
                data <- mtransform(data, list(mle.m1, mle.m2))
            }
        }
    }
    if (rev) 
        data <- data[, 2:1]
    data <- na.omit(data)
    if (plot || add) 
        x <- seq(0, 1, length = 100)
    d1 <- data[, 1]
    d2 <- data[, 2]
    sum1 <- sum(d1)
    slm1 <- sum(log(d1))
    sum2 <- sum(d2)
    slm2 <- sum(log(d2))
    nn <- nrow(data)
    nx <- length(x)
    mpmin <- function(a, b) {
        a[a > b] <- b[a > b]
        a
    }
    mpmax <- function(a, b) {
        a[a < b] <- b[a < b]
        a
    }
    if (method == "cfg") {
        if (!convex) {
            a <- numeric(nx)
            for (i in 1:nx) a[i] <- sum(log(mpmax((1 - x[i]) * 
                d1, x[i] * d2)))
            a <- (a - (1 - x) * slm1 - x * slm2)/nn
            a <- pmin(1, pmax(exp(a), x, 1 - x))
        }
        else {
            x2 <- seq(0, 1, length = 250)
            a <- numeric(250)
            for (i in 1:250) a[i] <- sum(log(mpmax((1 - x2[i]) * 
                d1, x2[i] * d2)))
            a <- (a - (1 - x2) * slm1 - x2 * slm2)/nn
            a <- pmin(1, pmax(exp(a), x2, 1 - x2))
            inch <- chull(x2, a)
            a <- a[inch]
            x2 <- x2[inch]
            a <- approx(x2, a, xout = x, method = "linear")$y
        }
    }
    if (method == "pickands") {
        if (!convex) {
            a <- numeric(nx)
            if (madj == 2) {
                d1 <- d1/mean(d1)
                d2 <- d2/mean(d2)
            }
            for (i in 1:nx) a[i] <- sum(mpmin(d1/x[i], d2/(1 - 
                x[i])))
            if (madj == 1) 
                a <- a - x * sum1 - (1 - x) * sum2 + nn
            a <- nn/a
            a <- pmin(1, pmax(a, x, 1 - x))
        }
        else {
            x2 <- seq(0, 1, length = 250)
            a <- numeric(250)
            if (madj == 2) {
                d1 <- d1/mean(d1)
                d2 <- d2/mean(d2)
            }
            for (i in 1:250) a[i] <- sum(mpmin(d1/x2[i], d2/(1 - 
                x2[i])))
            if (madj == 1) 
                a <- a - x2 * sum1 - (1 - x2) * sum2 + nn
            a <- nn/a
            a <- pmin(1, pmax(a, x2, 1 - x2))
            inch <- chull(x2, a)
            a <- a[inch]
            x2 <- x2[inch]
            a <- approx(x2, a, xout = x, method = "linear")$y
        }
    }
    if (method == "tdo") {
        if (!convex) {
            a <- numeric(nx)
            for (i in 1:nx) a[i] <- sum(mpmin(x[i]/(1 + nn * 
                d1), (1 - x[i])/(1 + nn * d2)))
            a <- 1 - a/(1 + log(nn))
            a <- pmin(1, pmax(a, x, 1 - x))
        }
        else {
            x2 <- seq(0, 1, length = 250)
            a <- numeric(250)
            for (i in 1:250) a[i] <- sum(mpmin(x2[i]/(1 + nn * 
                d1), (1 - x2[i])/(1 + nn * d2)))
            a <- 1 - a/(1 + log(nn))
            a <- pmin(1, pmax(a, x2, 1 - x2))
            inch <- chull(x2, a)
            a <- a[inch]
            x2 <- x2[inch]
            a <- approx(x2, a, xout = x, method = "linear")$y
        }
    }
    if (method == "pot") {
        a <- numeric(nx)
        rr <- rowSums(1/data)
        rrk <- sort(rr, decreasing = TRUE)[k + 1]
        for (i in 1:nx) a[i] <- sum(mpmax(x[i]/(d1 * rr), (1 - 
            x[i])/(d2 * rr))[rr > rrk])
        a <- 2/k * a
        a0 <- 2/k * sum(1/(d2 * rr)[rr > rrk])
        a1 <- 2/k * sum(1/(d1 * rr)[rr > rrk])
        a <- a + 1 - (1 - x) * a0 - x * a1
        a <- pmin(1, pmax(a, x, 1 - x))
    }
    if (plot || add) {
        if (!add) {
            plot(x, a, type = "n", xlab = xlab, ylab = ylab, 
                xlim = xlim, ylim = ylim, ...)
            polygon(c(0, 0.5, 1), c(1, 0.5, 1), lty = blty, lwd = blwd)
        }
        lines(x, a, lty = lty, lwd = lwd, col = col)
        return(invisible(list(x = x, y = a)))
    }
    a
}


```